import Footer from '@/components/footer'
import Navbar from '@/components/navbar'
import ScrollToTop from '@/components/ui/ScrollToTop'
import ModalProvider from '@/providers/modal-provider'
import ToastProvider from '@/providers/toast-provider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Urbanist } from 'next/font/google'

const font = Urbanist({ subsets: ['latin'] })

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ToastProvider />
        <ModalProvider />
        <Navbar />
        {children}
        {/* <Analytics /> */}
        <ScrollToTop/>
        <Footer />
      </body>
    </html>
  )
}